version: '3'
services:
  web:
    image: ruby/3.2.2
    build: .
    environment:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMINISTRATIVE_TOKEN: ${ADMINISTRATIVE_TOKEN}
      CONDO_API_DATABASE_HOSTNAME: ${CONDO_API_DATABASE_HOSTNAME}
      CONDO_API_DATABASE_PASSWORD: ${CONDO_API_DATABASE_PASSWORD}
      DOMAIN: ${DOMAIN}
      ELEVATOR_EMAIL_DELIVERY: ${ELEVATOR_EMAIL_DELIVERY}
      ELEVATOR_EMAIL_MOVE: ${ELEVATOR_EMAIL_MOVE}
      EMAIL: ${EMAIL}
      GMAIL_ACCOUNT: ${GMAIL_ACCOUNT}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
      NUMBER_OF_DAYS: ${NUMBER_OF_DAYS}
      RAILS_ENV: ${RAILS_ENV}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    command: bundle exec rails s -p 3000 -b '0.0.0.0' -e ${RAILS_ENV}
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    # tty: true
    # stdin_open: true
