# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AuthenticationMailer`.
# Please instead update this file by running `bin/tapioca dsl AuthenticationMailer`.


class AuthenticationMailer
  class << self
    sig { params(my_authentication: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def registration(my_authentication); end
  end
end
