# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AuthenticationsController`.
# Please instead update this file by running `bin/tapioca dsl AuthenticationsController`.


class AuthenticationsController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
