# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ElevatorMailer`.
# Please instead update this file by running `bin/tapioca dsl ElevatorMailer`.


class ElevatorMailer
  class << self
    sig { params(elevator_booking: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def approval(elevator_booking); end

    sig { params(elevator_booking: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def notification(elevator_booking); end

    sig { params(elevator_booking: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def pending(elevator_booking); end

    sig { params(elevator_booking: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def rejection(elevator_booking); end
  end
end
