# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GeneratedUrlHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl GeneratedUrlHelpersModule`.


module GeneratedUrlHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def authentication_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def authentications_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def create_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_authentication_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_elevator_booking_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_parking_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_question_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_reservation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_resource_question_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_resource_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def elevator_booking_approve_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def elevator_booking_reject_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def elevator_booking_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def elevator_bookings_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def find_reservations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def future_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def healthcheck_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def login_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def logout_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def mine_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_authentication_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_elevator_booking_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_parking_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_question_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_reservation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_resource_question_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_resource_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def parking_index_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def parking_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def past_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def process_login_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def question_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def questions_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_representation_proxy_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_representation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_direct_uploads_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_disk_service_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_notes_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_properties_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_routes_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mailers_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_representation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_service_blob_proxy_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_service_blob_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_storage_proxy_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_storage_redirect_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def remove_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def reservation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def reservations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def resource_question_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def resource_questions_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def resource_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def resources_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def today_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def update_rails_disk_service_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def upload_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def users_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def valid_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def webauthn_authenticate_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def webauthn_authentication_options_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def webauthn_check_availability_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def webauthn_credential_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def webauthn_credentials_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def webauthn_register_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def webauthn_registration_options_url(*args); end
end
