# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GeneratedPathHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl GeneratedPathHelpersModule`.


module GeneratedPathHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def authentication_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def authentications_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def create_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_authentication_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_elevator_booking_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_parking_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_question_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_reservation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_resource_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_resource_question_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def elevator_booking_approve_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def elevator_booking_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def elevator_booking_reject_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def elevator_bookings_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def find_reservations_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def future_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def healthcheck_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def login_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def logout_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def mine_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_authentication_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_elevator_booking_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_parking_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_question_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_reservation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_resource_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_resource_question_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def parking_index_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def parking_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def past_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def process_login_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def question_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def questions_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_representation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_representation_proxy_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_direct_uploads_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_disk_service_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_notes_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_properties_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_routes_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mailers_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_representation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_service_blob_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_service_blob_proxy_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_storage_proxy_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_storage_redirect_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def remove_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def reservation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def reservations_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def resource_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def resource_question_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def resource_questions_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def resources_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def today_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def update_rails_disk_service_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def upload_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def users_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def valid_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def webauthn_authenticate_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def webauthn_authentication_options_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def webauthn_check_availability_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def webauthn_credential_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def webauthn_credentials_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def webauthn_register_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def webauthn_registration_options_path(*args); end
end
