# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ParkingMailer`.
# Please instead update this file by running `bin/tapioca dsl ParkingMailer`.


class ParkingMailer
  class << self
    sig { params(parking: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def confirmation(parking); end

    sig { params(parking: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def registration(parking); end
  end
end
