# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ParkingController`.
# Please instead update this file by running `bin/tapioca dsl ParkingController`.


class ParkingController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
