# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `QuestionsController`.
# Please instead update this file by running `bin/tapioca dsl QuestionsController`.


class QuestionsController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
