# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ReservationsController`.
# Please instead update this file by running `bin/tapioca dsl ReservationsController`.


class ReservationsController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
