# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ResourceQuestionsController`.
# Please instead update this file by running `bin/tapioca dsl ResourceQuestionsController`.


class ResourceQuestionsController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
