# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ResourcesController`.
# Please instead update this file by running `bin/tapioca dsl ResourcesController`.


class ResourcesController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
