# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UsersController`.
# Please instead update this file by running `bin/tapioca dsl UsersController`.


class UsersController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
