# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `WebauthnCredentialsController`.
# Please instead update this file by running `bin/tapioca dsl WebauthnCredentialsController`.


class WebauthnCredentialsController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
