# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Healthcheck::HealthchecksController`.
# Please instead update this file by running `bin/tapioca dsl Healthcheck::HealthchecksController`.


class Healthcheck::HealthchecksController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule

  sig { returns(HelperProxy) }
  def helpers; end

  module HelperMethods
    include ::Webpacker::Helper
    include ::ActionController::Base::HelperMethods
    include ::ApplicationHelper
    include ::AuthenticationsHelper
    include ::ElevatorBookingsHelper
    include ::QuestionsHelper
    include ::ReservationsHelper
    include ::ResourceQuestionsHelper
    include ::ResourcesHelper
    include ::UsersHelper
  end

  class HelperProxy < ::ActionView::Base
    include HelperMethods
  end
end
