name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      env:
        SECRET_KEY_BASE: ${{ vars.SECRET_KEY_BASE }}
        RAILS_ENV: ${{ vars.RAILS_ENV }}
      run: docker compose build
